project:
  type: book
  output-dir: public

lang: fr

book:
  title: "Retraites"
  author: "Mahdi Ben Jelloul"
  repo-url: https://github.com/benjello/precis-socio-fiscal-tunisie/
  repo-subdir: precis/ar/retraites
  repo-branch: master
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - _secteur_public.qmd
    - _secteur_prive.qmd

bibliography: ../references.bib

format:
  html:
    theme: cosmo
    number-depth: 3
    toc: true
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
