preserve_hierarchy: true

files:
  # Traduction des chapitres Markdown
  - source: /precis/**/*.qmd
    translation: /precis/%two_letters_code%/**/%original_file_name%
    
  # Traduction des configurations Quarto (titres des livres)
  - source: /precis/**/_quarto.yml
    translation: /precis/%two_letters_code%/**/_quarto.yml
