---
title: "Précis de la législation socio-fiscale de la Tunisie"
subtitle: "Historique et cadre législatif des politiques publiques en Tunisie"
---

Bienvenue sur le portail documentaire interactif du système socio-fiscal tunisien. Ce portail vise à documenter les évolutions de la législation sociale et fiscale depuis l'indépendance de la Tunisie en 1956 et à permettre aux experts (juristes, économistes, responsables de politiques publiques) d'y contribuer de manière collaborative.

## Précis disponibles

::: {.grid}

::: {.g-col-12 .g-col-md-6 .g-col-lg-6}
### [Les prestations sociales](./prestations_sociales/)
Les programmes d’aide et d’assistance sociale, de soutien à l’emploi, et les différentes prestations monétaires et non monétaires.
:::

::: {.g-col-12 .g-col-md-6 .g-col-lg-6}
### [Le système de retraite](./retraites/)
Historique et fonctionnement du système de retraite par répartition en Tunisie (secteur public et secteur privé).
:::

::: {.g-col-12 .g-col-md-6 .g-col-lg-6}
### [Les cotisations sociales](#) *(en développement)*
Calcul et évolution des cotisations sociales et autres prélèvements obligatoires sur les revenus du travail.
:::

::: {.g-col-12 .g-col-md-6 .g-col-lg-6}
### [La fiscalité](#) *(en développement)*
Le système fiscal tunisien.
:::

:::
